package com.example.palmarlibrary;

import android.animation.Animator;
import android.animation.AnimatorInflater;
import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.os.Handler;
import android.os.Message;
import android.support.annotation.Nullable;
import android.util.Log;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;

import java.util.Timer;
import java.util.TimerTask;

/**
 * Created by as on 2018/5/16.
 */

public class welcomeActivity extends Activity {
    public void enterHome(){
        Timer time = new Timer();
        TimerTask tk = new TimerTask() {
            Intent intent = new Intent(welcomeActivity.this,choseprovinceActivity.class);
            @Override
            public void run() {
                // TODO Auto-generated method stub

                startActivity(intent);
                finish();
            }
        };time.schedule(tk, 5000);

    }
    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        final int[] i = {5};
        i[0]=5;
        super.onCreate(savedInstanceState);
        setContentView(R.layout.welcome_layout);
        final TextView[] view = {findViewById(R.id.anima)};
        Animator animator = AnimatorInflater.loadAnimator(this, R.animator.set_animation); // 载入XML动画
        animator.setTarget(view[0]); // 设置动画对象
        animator.setDuration(5000);//shichang
        animator.setStartDelay(500);
        animator.start();
        final TextView btn = findViewById(R.id.tz);
        enterHome();
        class MyTask extends TimerTask {

            @Override
            public void run() {

                btn.setText("跳转("+ i[0]+")");
                i[0] = i[0]-1;

            }

        }
        class M {

            public void main() {
                // TODO todo.generated by zoer
                Timer timer = new Timer();
                timer.schedule(new MyTask(), 0, 1000);
            }
        }

        M m = new M();
        m.main();



        btn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent intent = new Intent(welcomeActivity.this,choseprovinceActivity.class);
                startActivity(intent);
            }
        });
    }
}
